// <auto-generated />
namespace MasterGroup.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class HopefullyThisWorks : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(HopefullyThisWorks));
        
        string IMigrationMetadata.Id
        {
            get { return "201910151259150_HopefullyThisWorks"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
